name: LongHardFish
version: 1.0
main: org.aincraft.LongHardFish
api-version: 1.20

commands:
  fishstats:
    description: Show top caught fish
    usage: "/fishstats [player] [limit]"
    permission: longhardfish.stats
  fishdex:
    description: Open the FishDex for a specific fish id
    usage: /fishdex <fish-id>
  lhfgive:
    description: Give a registered LongHardFish custom item
    usage: /lhfgive <item-id> [player] [amount]
    permission: longhardfish.give
    aliases: [ lhf-give, lhfitem, lhf-item ]

permissions:
  longhardfish.stats:
    description: Use /fishstats to view stats
    default: true
  longhardfish.give:
    default: op