name: LongHardFish
version: 1.0
main: org.aincraft.LongHardFish
api-version: 1.20

commands:
  fishstats:
    description: Show top caught fish
    usage: "/fishstats [player] [limit]"
    permission: longhardfish.stats
  fishdex:
    description: Open the FishDex for a specific fish id
    usage: /fishdex <fish-id>
  lhfgive:
    description: Give a registered LongHardFish custom item
    usage: /lhfgive <item-id> [player] [amount] OR  /<command> rod <rod-id> [player]
    permission: longhardfish.give
    aliases: [ lhf-give, lhfitem, lhf-item ]
  lhf-give:
    description: Give LongHardFish special items/blocks
    usage: /<command> gutting_station [amount] OR /<command> <player> gutting_station [amount]
    permission: lhf.admin
  tacklebox:
    description: Open the Tackle Box GUI
    usage: /tacklebox
    permission: longhardfish.tacklebox
  fishgut:
    description: Open the fish processor GUI
    usage: /fishgut
    permission: longhardfish.gut
  lhf-fishdex:
    description: LongHardFish admin fishdex tools
    usage: /<command> <player> ...
    permission: lhf.admin

permissions:
  longhardfish.stats:
    description: Use /fishstats to view stats
    default: true
  longhardfish.give:
    default: op
  longhardfish.tacklebox:
    default: true
  longhardfish.fishprocessor:
    default: true
  lhf.admin:
    description: Admin permission for LongHardFish utilities
    default: op